# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import market_data_pb2 as market__data__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in market_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketDataStreamerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamPrices = channel.unary_stream(
                '/marketdata.MarketDataStreamer/StreamPrices',
                request_serializer=market__data__pb2.PriceRequest.SerializeToString,
                response_deserializer=market__data__pb2.PriceUpdate.FromString,
                _registered_method=True)
        self.SendPrice = channel.unary_unary(
                '/marketdata.MarketDataStreamer/SendPrice',
                request_serializer=market__data__pb2.PriceUpdate.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class MarketDataStreamerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamPrices(self, request, context):
        """Client subscribes to real-time prices.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPrice(self, request, context):
        """External source (e.g., Python WebSocket) pushes price updates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketDataStreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamPrices': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPrices,
                    request_deserializer=market__data__pb2.PriceRequest.FromString,
                    response_serializer=market__data__pb2.PriceUpdate.SerializeToString,
            ),
            'SendPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPrice,
                    request_deserializer=market__data__pb2.PriceUpdate.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketdata.MarketDataStreamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketdata.MarketDataStreamer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketDataStreamer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/marketdata.MarketDataStreamer/StreamPrices',
            market__data__pb2.PriceRequest.SerializeToString,
            market__data__pb2.PriceUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketdata.MarketDataStreamer/SendPrice',
            market__data__pb2.PriceUpdate.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
