// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: market_data.proto
// Protobuf C++ Version: 5.29.3

#include "market_data.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace marketdata {

inline constexpr PriceUpdate::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : symbol_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        price_{0},
        timestamp_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PriceUpdate::PriceUpdate(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PriceUpdateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PriceUpdateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PriceUpdateDefaultTypeInternal() {}
  union {
    PriceUpdate _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PriceUpdateDefaultTypeInternal _PriceUpdate_default_instance_;

inline constexpr PriceRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : symbols_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PriceRequest::PriceRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PriceRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PriceRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PriceRequestDefaultTypeInternal() {}
  union {
    PriceRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PriceRequestDefaultTypeInternal _PriceRequest_default_instance_;
}  // namespace marketdata
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_market_5fdata_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_market_5fdata_2eproto = nullptr;
const ::uint32_t
    TableStruct_market_5fdata_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::marketdata::PriceRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::marketdata::PriceRequest, _impl_.symbols_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::marketdata::PriceUpdate, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::marketdata::PriceUpdate, _impl_.symbol_),
        PROTOBUF_FIELD_OFFSET(::marketdata::PriceUpdate, _impl_.price_),
        PROTOBUF_FIELD_OFFSET(::marketdata::PriceUpdate, _impl_.timestamp_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::marketdata::PriceRequest)},
        {9, -1, -1, sizeof(::marketdata::PriceUpdate)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::marketdata::_PriceRequest_default_instance_._instance,
    &::marketdata::_PriceUpdate_default_instance_._instance,
};
const char descriptor_table_protodef_market_5fdata_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021market_data.proto\022\nmarketdata\032\033google/"
    "protobuf/empty.proto\"\037\n\014PriceRequest\022\017\n\007"
    "symbols\030\001 \003(\t\"\?\n\013PriceUpdate\022\016\n\006symbol\030\001"
    " \001(\t\022\r\n\005price\030\002 \001(\001\022\021\n\ttimestamp\030\003 \001(\0032\227"
    "\001\n\022MarketDataStreamer\022C\n\014StreamPrices\022\030."
    "marketdata.PriceRequest\032\027.marketdata.Pri"
    "ceUpdate0\001\022<\n\tSendPrice\022\027.marketdata.Pri"
    "ceUpdate\032\026.google.protobuf.Emptyb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_market_5fdata_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::absl::once_flag descriptor_table_market_5fdata_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_market_5fdata_2eproto = {
    false,
    false,
    320,
    descriptor_table_protodef_market_5fdata_2eproto,
    "market_data.proto",
    &descriptor_table_market_5fdata_2eproto_once,
    descriptor_table_market_5fdata_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_market_5fdata_2eproto::offsets,
    file_level_enum_descriptors_market_5fdata_2eproto,
    file_level_service_descriptors_market_5fdata_2eproto,
};
namespace marketdata {
// ===================================================================

class PriceRequest::_Internal {
 public:
};

PriceRequest::PriceRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:marketdata.PriceRequest)
}
inline PROTOBUF_NDEBUG_INLINE PriceRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::marketdata::PriceRequest& from_msg)
      : symbols_{visibility, arena, from.symbols_},
        _cached_size_{0} {}

PriceRequest::PriceRequest(
    ::google::protobuf::Arena* arena,
    const PriceRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PriceRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:marketdata.PriceRequest)
}
inline PROTOBUF_NDEBUG_INLINE PriceRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : symbols_{visibility, arena},
        _cached_size_{0} {}

inline void PriceRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PriceRequest::~PriceRequest() {
  // @@protoc_insertion_point(destructor:marketdata.PriceRequest)
  SharedDtor(*this);
}
inline void PriceRequest::SharedDtor(MessageLite& self) {
  PriceRequest& this_ = static_cast<PriceRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PriceRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) PriceRequest(arena);
}
constexpr auto PriceRequest::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(PriceRequest, _impl_.symbols_) +
          decltype(PriceRequest::_impl_.symbols_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(PriceRequest), alignof(PriceRequest), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&PriceRequest::PlacementNew_,
                                 sizeof(PriceRequest),
                                 alignof(PriceRequest));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull PriceRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_PriceRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &PriceRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<PriceRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &PriceRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<PriceRequest>(), &PriceRequest::ByteSizeLong,
            &PriceRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(PriceRequest, _impl_._cached_size_),
        false,
    },
    &PriceRequest::kDescriptorMethods,
    &descriptor_table_market_5fdata_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* PriceRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 39, 2> PriceRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::marketdata::PriceRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string symbols = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PriceRequest, _impl_.symbols_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string symbols = 1;
    {PROTOBUF_FIELD_OFFSET(PriceRequest, _impl_.symbols_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\27\7\0\0\0\0\0\0"
    "marketdata.PriceRequest"
    "symbols"
  }},
};

PROTOBUF_NOINLINE void PriceRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:marketdata.PriceRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.symbols_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PriceRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PriceRequest& this_ = static_cast<const PriceRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PriceRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PriceRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:marketdata.PriceRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated string symbols = 1;
          for (int i = 0, n = this_._internal_symbols_size(); i < n; ++i) {
            const auto& s = this_._internal_symbols().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "marketdata.PriceRequest.symbols");
            target = stream->WriteString(1, s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:marketdata.PriceRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PriceRequest::ByteSizeLong(const MessageLite& base) {
          const PriceRequest& this_ = static_cast<const PriceRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PriceRequest::ByteSizeLong() const {
          const PriceRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:marketdata.PriceRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string symbols = 1;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_symbols().size());
              for (int i = 0, n = this_._internal_symbols().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_symbols().Get(i));
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PriceRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PriceRequest*>(&to_msg);
  auto& from = static_cast<const PriceRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:marketdata.PriceRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_symbols()->MergeFrom(from._internal_symbols());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PriceRequest::CopyFrom(const PriceRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:marketdata.PriceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PriceRequest::InternalSwap(PriceRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.symbols_.InternalSwap(&other->_impl_.symbols_);
}

::google::protobuf::Metadata PriceRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PriceUpdate::_Internal {
 public:
};

PriceUpdate::PriceUpdate(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:marketdata.PriceUpdate)
}
inline PROTOBUF_NDEBUG_INLINE PriceUpdate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::marketdata::PriceUpdate& from_msg)
      : symbol_(arena, from.symbol_),
        _cached_size_{0} {}

PriceUpdate::PriceUpdate(
    ::google::protobuf::Arena* arena,
    const PriceUpdate& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PriceUpdate* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, price_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, price_),
           offsetof(Impl_, timestamp_) -
               offsetof(Impl_, price_) +
               sizeof(Impl_::timestamp_));

  // @@protoc_insertion_point(copy_constructor:marketdata.PriceUpdate)
}
inline PROTOBUF_NDEBUG_INLINE PriceUpdate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : symbol_(arena),
        _cached_size_{0} {}

inline void PriceUpdate::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, price_),
           0,
           offsetof(Impl_, timestamp_) -
               offsetof(Impl_, price_) +
               sizeof(Impl_::timestamp_));
}
PriceUpdate::~PriceUpdate() {
  // @@protoc_insertion_point(destructor:marketdata.PriceUpdate)
  SharedDtor(*this);
}
inline void PriceUpdate::SharedDtor(MessageLite& self) {
  PriceUpdate& this_ = static_cast<PriceUpdate&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.symbol_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PriceUpdate::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) PriceUpdate(arena);
}
constexpr auto PriceUpdate::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PriceUpdate),
                                            alignof(PriceUpdate));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull PriceUpdate::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_PriceUpdate_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &PriceUpdate::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<PriceUpdate>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &PriceUpdate::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<PriceUpdate>(), &PriceUpdate::ByteSizeLong,
            &PriceUpdate::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(PriceUpdate, _impl_._cached_size_),
        false,
    },
    &PriceUpdate::kDescriptorMethods,
    &descriptor_table_market_5fdata_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* PriceUpdate::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 37, 2> PriceUpdate::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::marketdata::PriceUpdate>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string symbol = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PriceUpdate, _impl_.symbol_)}},
    // double price = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(PriceUpdate, _impl_.price_)}},
    // int64 timestamp = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PriceUpdate, _impl_.timestamp_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(PriceUpdate, _impl_.timestamp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string symbol = 1;
    {PROTOBUF_FIELD_OFFSET(PriceUpdate, _impl_.symbol_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double price = 2;
    {PROTOBUF_FIELD_OFFSET(PriceUpdate, _impl_.price_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // int64 timestamp = 3;
    {PROTOBUF_FIELD_OFFSET(PriceUpdate, _impl_.timestamp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\26\6\0\0\0\0\0\0"
    "marketdata.PriceUpdate"
    "symbol"
  }},
};

PROTOBUF_NOINLINE void PriceUpdate::Clear() {
// @@protoc_insertion_point(message_clear_start:marketdata.PriceUpdate)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.symbol_.ClearToEmpty();
  ::memset(&_impl_.price_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.timestamp_) -
      reinterpret_cast<char*>(&_impl_.price_)) + sizeof(_impl_.timestamp_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PriceUpdate::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PriceUpdate& this_ = static_cast<const PriceUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PriceUpdate::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PriceUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:marketdata.PriceUpdate)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string symbol = 1;
          if (!this_._internal_symbol().empty()) {
            const std::string& _s = this_._internal_symbol();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "marketdata.PriceUpdate.symbol");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // double price = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_price()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_price(), target);
          }

          // int64 timestamp = 3;
          if (this_._internal_timestamp() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<3>(
                    stream, this_._internal_timestamp(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:marketdata.PriceUpdate)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PriceUpdate::ByteSizeLong(const MessageLite& base) {
          const PriceUpdate& this_ = static_cast<const PriceUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PriceUpdate::ByteSizeLong() const {
          const PriceUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:marketdata.PriceUpdate)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string symbol = 1;
            if (!this_._internal_symbol().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_symbol());
            }
            // double price = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_price()) != 0) {
              total_size += 9;
            }
            // int64 timestamp = 3;
            if (this_._internal_timestamp() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_timestamp());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PriceUpdate::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PriceUpdate*>(&to_msg);
  auto& from = static_cast<const PriceUpdate&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:marketdata.PriceUpdate)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_symbol().empty()) {
    _this->_internal_set_symbol(from._internal_symbol());
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_price()) != 0) {
    _this->_impl_.price_ = from._impl_.price_;
  }
  if (from._internal_timestamp() != 0) {
    _this->_impl_.timestamp_ = from._impl_.timestamp_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PriceUpdate::CopyFrom(const PriceUpdate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:marketdata.PriceUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PriceUpdate::InternalSwap(PriceUpdate* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.symbol_, &other->_impl_.symbol_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PriceUpdate, _impl_.timestamp_)
      + sizeof(PriceUpdate::_impl_.timestamp_)
      - PROTOBUF_FIELD_OFFSET(PriceUpdate, _impl_.price_)>(
          reinterpret_cast<char*>(&_impl_.price_),
          reinterpret_cast<char*>(&other->_impl_.price_));
}

::google::protobuf::Metadata PriceUpdate::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace marketdata
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_market_5fdata_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
