# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: market_data.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'market_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11market_data.proto\x12\nmarketdata\x1a\x1bgoogle/protobuf/empty.proto\"\x1f\n\x0cPriceRequest\x12\x0f\n\x07symbols\x18\x01 \x03(\t\"?\n\x0bPriceUpdate\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x32\x97\x01\n\x12MarketDataStreamer\x12\x43\n\x0cStreamPrices\x12\x18.marketdata.PriceRequest\x1a\x17.marketdata.PriceUpdate0\x01\x12<\n\tSendPrice\x12\x17.marketdata.PriceUpdate\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRICEREQUEST']._serialized_start=62
  _globals['_PRICEREQUEST']._serialized_end=93
  _globals['_PRICEUPDATE']._serialized_start=95
  _globals['_PRICEUPDATE']._serialized_end=158
  _globals['_MARKETDATASTREAMER']._serialized_start=161
  _globals['_MARKETDATASTREAMER']._serialized_end=312
# @@protoc_insertion_point(module_scope)
