// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: market_data.proto
// Original file comments:
// proto/market_data.proto
//
// Market Data Streaming API using gRPC.
// This defines the service and messages used for subscribing to real-time prices,
// and for submitting external price ticks (e.g., from a WebSocket feed).
//
#ifndef GRPC_market_5fdata_2eproto__INCLUDED
#define GRPC_market_5fdata_2eproto__INCLUDED

#include "market_data.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace marketdata {

class MarketDataStreamer final {
 public:
  static constexpr char const* service_full_name() {
    return "marketdata.MarketDataStreamer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Client subscribes to real-time prices.
    std::unique_ptr< ::grpc::ClientReaderInterface< ::marketdata::PriceUpdate>> StreamPrices(::grpc::ClientContext* context, const ::marketdata::PriceRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::marketdata::PriceUpdate>>(StreamPricesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::marketdata::PriceUpdate>> AsyncStreamPrices(::grpc::ClientContext* context, const ::marketdata::PriceRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::marketdata::PriceUpdate>>(AsyncStreamPricesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::marketdata::PriceUpdate>> PrepareAsyncStreamPrices(::grpc::ClientContext* context, const ::marketdata::PriceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::marketdata::PriceUpdate>>(PrepareAsyncStreamPricesRaw(context, request, cq));
    }
    // External source (e.g., Python WebSocket) pushes price updates.
    virtual ::grpc::Status SendPrice(::grpc::ClientContext* context, const ::marketdata::PriceUpdate& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncSendPrice(::grpc::ClientContext* context, const ::marketdata::PriceUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncSendPriceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> PrepareAsyncSendPrice(::grpc::ClientContext* context, const ::marketdata::PriceUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(PrepareAsyncSendPriceRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Client subscribes to real-time prices.
      virtual void StreamPrices(::grpc::ClientContext* context, const ::marketdata::PriceRequest* request, ::grpc::ClientReadReactor< ::marketdata::PriceUpdate>* reactor) = 0;
      // External source (e.g., Python WebSocket) pushes price updates.
      virtual void SendPrice(::grpc::ClientContext* context, const ::marketdata::PriceUpdate* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendPrice(::grpc::ClientContext* context, const ::marketdata::PriceUpdate* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::marketdata::PriceUpdate>* StreamPricesRaw(::grpc::ClientContext* context, const ::marketdata::PriceRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::marketdata::PriceUpdate>* AsyncStreamPricesRaw(::grpc::ClientContext* context, const ::marketdata::PriceRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::marketdata::PriceUpdate>* PrepareAsyncStreamPricesRaw(::grpc::ClientContext* context, const ::marketdata::PriceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncSendPriceRaw(::grpc::ClientContext* context, const ::marketdata::PriceUpdate& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* PrepareAsyncSendPriceRaw(::grpc::ClientContext* context, const ::marketdata::PriceUpdate& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::marketdata::PriceUpdate>> StreamPrices(::grpc::ClientContext* context, const ::marketdata::PriceRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::marketdata::PriceUpdate>>(StreamPricesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::marketdata::PriceUpdate>> AsyncStreamPrices(::grpc::ClientContext* context, const ::marketdata::PriceRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::marketdata::PriceUpdate>>(AsyncStreamPricesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::marketdata::PriceUpdate>> PrepareAsyncStreamPrices(::grpc::ClientContext* context, const ::marketdata::PriceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::marketdata::PriceUpdate>>(PrepareAsyncStreamPricesRaw(context, request, cq));
    }
    ::grpc::Status SendPrice(::grpc::ClientContext* context, const ::marketdata::PriceUpdate& request, ::google::protobuf::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncSendPrice(::grpc::ClientContext* context, const ::marketdata::PriceUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncSendPriceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> PrepareAsyncSendPrice(::grpc::ClientContext* context, const ::marketdata::PriceUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(PrepareAsyncSendPriceRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StreamPrices(::grpc::ClientContext* context, const ::marketdata::PriceRequest* request, ::grpc::ClientReadReactor< ::marketdata::PriceUpdate>* reactor) override;
      void SendPrice(::grpc::ClientContext* context, const ::marketdata::PriceUpdate* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) override;
      void SendPrice(::grpc::ClientContext* context, const ::marketdata::PriceUpdate* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::marketdata::PriceUpdate>* StreamPricesRaw(::grpc::ClientContext* context, const ::marketdata::PriceRequest& request) override;
    ::grpc::ClientAsyncReader< ::marketdata::PriceUpdate>* AsyncStreamPricesRaw(::grpc::ClientContext* context, const ::marketdata::PriceRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::marketdata::PriceUpdate>* PrepareAsyncStreamPricesRaw(::grpc::ClientContext* context, const ::marketdata::PriceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncSendPriceRaw(::grpc::ClientContext* context, const ::marketdata::PriceUpdate& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* PrepareAsyncSendPriceRaw(::grpc::ClientContext* context, const ::marketdata::PriceUpdate& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StreamPrices_;
    const ::grpc::internal::RpcMethod rpcmethod_SendPrice_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Client subscribes to real-time prices.
    virtual ::grpc::Status StreamPrices(::grpc::ServerContext* context, const ::marketdata::PriceRequest* request, ::grpc::ServerWriter< ::marketdata::PriceUpdate>* writer);
    // External source (e.g., Python WebSocket) pushes price updates.
    virtual ::grpc::Status SendPrice(::grpc::ServerContext* context, const ::marketdata::PriceUpdate* request, ::google::protobuf::Empty* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamPrices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamPrices() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StreamPrices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPrices(::grpc::ServerContext* /*context*/, const ::marketdata::PriceRequest* /*request*/, ::grpc::ServerWriter< ::marketdata::PriceUpdate>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamPrices(::grpc::ServerContext* context, ::marketdata::PriceRequest* request, ::grpc::ServerAsyncWriter< ::marketdata::PriceUpdate>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SendPrice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendPrice() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SendPrice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPrice(::grpc::ServerContext* /*context*/, const ::marketdata::PriceUpdate* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendPrice(::grpc::ServerContext* context, ::marketdata::PriceUpdate* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StreamPrices<WithAsyncMethod_SendPrice<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StreamPrices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamPrices() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::marketdata::PriceRequest, ::marketdata::PriceUpdate>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::marketdata::PriceRequest* request) { return this->StreamPrices(context, request); }));
    }
    ~WithCallbackMethod_StreamPrices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPrices(::grpc::ServerContext* /*context*/, const ::marketdata::PriceRequest* /*request*/, ::grpc::ServerWriter< ::marketdata::PriceUpdate>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::marketdata::PriceUpdate>* StreamPrices(
      ::grpc::CallbackServerContext* /*context*/, const ::marketdata::PriceRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SendPrice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendPrice() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::marketdata::PriceUpdate, ::google::protobuf::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::marketdata::PriceUpdate* request, ::google::protobuf::Empty* response) { return this->SendPrice(context, request, response); }));}
    void SetMessageAllocatorFor_SendPrice(
        ::grpc::MessageAllocator< ::marketdata::PriceUpdate, ::google::protobuf::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::marketdata::PriceUpdate, ::google::protobuf::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendPrice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPrice(::grpc::ServerContext* /*context*/, const ::marketdata::PriceUpdate* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendPrice(
      ::grpc::CallbackServerContext* /*context*/, const ::marketdata::PriceUpdate* /*request*/, ::google::protobuf::Empty* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_StreamPrices<WithCallbackMethod_SendPrice<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StreamPrices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamPrices() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StreamPrices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPrices(::grpc::ServerContext* /*context*/, const ::marketdata::PriceRequest* /*request*/, ::grpc::ServerWriter< ::marketdata::PriceUpdate>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SendPrice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendPrice() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SendPrice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPrice(::grpc::ServerContext* /*context*/, const ::marketdata::PriceUpdate* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamPrices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamPrices() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StreamPrices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPrices(::grpc::ServerContext* /*context*/, const ::marketdata::PriceRequest* /*request*/, ::grpc::ServerWriter< ::marketdata::PriceUpdate>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamPrices(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendPrice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendPrice() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SendPrice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPrice(::grpc::ServerContext* /*context*/, const ::marketdata::PriceUpdate* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendPrice(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamPrices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamPrices() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->StreamPrices(context, request); }));
    }
    ~WithRawCallbackMethod_StreamPrices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPrices(::grpc::ServerContext* /*context*/, const ::marketdata::PriceRequest* /*request*/, ::grpc::ServerWriter< ::marketdata::PriceUpdate>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamPrices(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendPrice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendPrice() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendPrice(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendPrice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPrice(::grpc::ServerContext* /*context*/, const ::marketdata::PriceUpdate* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendPrice(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendPrice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendPrice() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::marketdata::PriceUpdate, ::google::protobuf::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::marketdata::PriceUpdate, ::google::protobuf::Empty>* streamer) {
                       return this->StreamedSendPrice(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendPrice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendPrice(::grpc::ServerContext* /*context*/, const ::marketdata::PriceUpdate* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendPrice(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::marketdata::PriceUpdate,::google::protobuf::Empty>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendPrice<Service > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamPrices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamPrices() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::marketdata::PriceRequest, ::marketdata::PriceUpdate>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::marketdata::PriceRequest, ::marketdata::PriceUpdate>* streamer) {
                       return this->StreamedStreamPrices(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamPrices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamPrices(::grpc::ServerContext* /*context*/, const ::marketdata::PriceRequest* /*request*/, ::grpc::ServerWriter< ::marketdata::PriceUpdate>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamPrices(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::marketdata::PriceRequest,::marketdata::PriceUpdate>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_StreamPrices<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_StreamPrices<WithStreamedUnaryMethod_SendPrice<Service > > StreamedService;
};

}  // namespace marketdata


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_market_5fdata_2eproto__INCLUDED
